### ISSUE TITLE
点击播放时显示连接失败

### ISSUE THREAD

**Issue by libraxin** [gaodeng/Moon-FM-Support#46]
ios12.b3

1、在时间线上点击某些节目的播放按钮时会出现“连接失败”，而在订阅里面点击同样的节目却可以播放

2、时间线上获取某些播客时会一直超时，多次刷新也一样

网络是正常的

**Comment by gaodeng** [comment]
Hi,
要是再次碰到这个问题的话，请告诉我一下具体是那一期节目，这样我比较好重现问题。

**Comment by GreyGao** [comment]
安卓8.0
live电台里Japan区域的NHK那几个电台也显示连接失败呢 不知道是不是源的问题 梯子也无效

**Comment by gaodeng** [comment]
连接失败估计是播放源失效了
