### ISSUE TITLE
同步功能如何使用？

### ISSUE THREAD

**Issue by 0verflew** [gaodeng/Moon-FM-Support#52]
你好，感谢moon fm的优美高效，但是我不太明白同步功能如何使用，请问能否加入更详细的说明呢？

**Comment by gaodeng** [comment]
同步功能还在内测中。

**Comment by gaodeng** [comment]
Couchdb 同步配置
https://github.com/gaodeng/Moon-FM-Support/blob/master/couchdb_setup/couchdb.md
