### ISSUE TITLE
希望同步功能可以支持 Web DAV 

### ISSUE THREAD

**Issue by sooxin** [gaodeng/Moon-FM-Support#62]
目前好像只能是添加一个远程 Couch DB。如果添加 Web DAV 支持的话，就可以使用 Dropbox 或者坚果云之类的云盘进行同步了。
感谢作者的辛勤付出，创造了这么好用的播客app。

**Comment by womeimingzi11** [comment]
附议！毕竟对于多设备用户来说，没有同步确实缺失了一大块！现在的 CouchDB 倒也不是不可以学习创建，但是没有 VPS 也不方便。Web DAV 能让同步变得可用

**Comment by HUANGvia** [comment]
是的，非常希望作者能够添加Web DAV 同步功能。

**Comment by howel52** [comment]
iOS 生态可以考虑 iCloud

**Comment by gaodeng** [comment]
Web DAV 只适合做备份，无法用来做数据同步，会产生数据冲突。iCloud 的问题是不能跨平台。
