### ISSUE TITLE
Airpods断开后，会自动使用扬声器继续播放。

### ISSUE THREAD

**Issue by Lesincs** [gaodeng/Moon-FM-Support#66]
场景：使用Airpods正常播放 --> 点击暂停 -->然后取下Airpods，此时由于系统得知两个耳机取下所以断开Airpods连接，此时，Moon-FM会自动开始播放，并使用扬声器；经试验，一些知名的音乐类APP均不会这样，对于办公室一族很不方便，希望改进或者加一个选项。

**Comment by gaodeng** [comment]
感谢。新版本已修复。
