### ISSUE TITLE
Android端的惯性滚动问题

### ISSUE THREAD

**Issue by Alphabet1226** [gaodeng/Moon-FM-Support#80]
首页的惯性滚动特性经常性失效。
通常情况下第一次打开App时都是有效的，但只要点一下“发现”页，再点回来“首页”，惯性滚动就会突然失效。希望可以修复。

**Comment by gaodeng** [comment]
请问你是什么品牌手机呢，另外系统版本以及android 版本是多少呢。这个问题以前好像很少碰到。

**Comment by Alphabet1226** [comment]
> 请问你是什么品牌手机呢，另外系统版本以及android 版本是多少呢。这个问题以前好像很少碰到。

手机是Redmi K20 Pro，系统为Evolution X，版本为Android 10。之前在其它ROM上也经常遇到这个问题。

**Comment by gaodeng** [comment]
> > 请问你是什么品牌手机呢，另外系统版本以及android 版本是多少呢。这个问题以前好像很少碰到。
> 
> 手机是Redmi K20 Pro，系统为Evolution X，版本为Android 10。之前在其它ROM上也经常遇到这个问题。

其他 app 碰到过这个问题吗

**Comment by Alphabet1226** [comment]
> > > 请问你是什么品牌手机呢，另外系统版本以及android 版本是多少呢。这个问题以前好像很少碰到。
> > 
> > 
> > 手机是Redmi K20 Pro，系统为Evolution X，版本为Android 10。之前在其它ROM上也经常遇到这个问题。
> 
> 其他 app 碰到过这个问题吗

其它APP暂时没有发现有这个问题。

**Comment by gaodeng** [comment]
收到。等啥时候我看能不能弄个Redmi 试试。

**Comment by gaodeng** [comment]
目前无法复现，修复不了
