### ISSUE TITLE
求一个跳过空白/无声段落

### ISSUE THREAD

**Issue by publicclassoverflow** [gaodeng/Moon-FM-Support#81]
好像有不少现成的算法可以用，之前总吐槽小宇宙结果它们加了这功能，感觉用的是Google podcasts的算法，跳得挺极端但还挺好用的。。Pocket casts比较合适，省时但没出现过丢词的现象。。现在阻止我从Pocket casts回来的就这个功能了。。小宇宙就别提了，那通知栏。。那评论区。。听个播客还想约炮，即刻真是魔怔了🐶大佬加油

**Comment by gaodeng** [comment]
可以能是因为都是用的 [google/ExoPlayer ](https://github.com/google/ExoPlayer) 处理的，所以效果差不多吧。
非常抱歉，跳过空白不计划做了。
这个功能节省的时间非常有限，但是却导致听到的不是原汁原味的节目。如果需要节省时间，最直接的方式是倍速播放。

**Comment by publicclassoverflow** [comment]
感谢老哥，问题不大。跟你讨论一下个人使用感受，跳空白其实能节省相当多的时间，我发现很多中文播客一期节目动辄就是一个小时往上，两个小时的都不少，是的我说的就是翻电什么的。。而且我们中文这种一字一音节，顿挫之间会有很多空白出现，我试着完了下两倍速听梁文道的八分，四五十分钟的节目，开跳白基本上能快七八分钟。。。至于你说原汁原味的节目，那当然有道理，比如听音乐节目，哪怕两个小时我也是原速不跳白肯定，这也是你做了单个节目播放设置的原因之一吧？Pocketcasts也是这样，单个节目设置好就好。app很棒，没有这功能也会一直支持下去lol

**Comment by publicclassoverflow** [comment]
抱歉这么久忘了关。。
