### ISSUE TITLE
能否关闭锁屏封面

### ISSUE THREAD

**Issue by zyfzyfhaha** [gaodeng/Moon-FM-Support#86]
![Screenshot_20201024-012451](https://user-images.githubusercontent.com/13297061/97034595-bcfeeb00-1597-11eb-91f3-03b38dbbea83.jpg)

**Comment by gaodeng** [comment]
hi, 这个问题需要给系统厂商反映。 这个是系统厂商自动从当前播放的节目信息里面提取了封面后，覆盖了你的锁屏壁纸。这个是很早 原生 android 的做法, 大多数时候显示效果都非常不好，所以 android 后续版本中取消了这种做法，但是可惜的是，有些厂商定制系统的时候，没有跟上节奏，即使新系统中还是延续了这种不好的做法。

**Comment by zyfzyfhaha** [comment]
感谢您的及时回复，确实我是用一加手机，系统比较原生。不过我有一个小问题，之前也试用过“小宇宙”那款播客app，在最初版本也是和moonfm一样有封面，在之后的更新版本中已经解决了这个问题。

**Comment by gaodeng** [comment]
> 感谢您的及时回复，确实我是用一加手机，系统比较原生。不过我有一个小问题，之前也试用过“小宇宙”那款播客app，在最初版本也是和moonfm一样有封面，在之后的更新版本中已经解决了这个问题。

其实原生android系统只有早期几个版本是这么做的，后来早就不这么做了，只是有些厂商定制系统后来没有跟上。当然可以用最粗暴的方法来解决，比如不让系统知道当前播放的节目信息，系统就不会去覆盖锁屏了。但是这虽然解决了这个问题，会给其他正常的系统带来问题，比如三星 one ui，系统会利用当前播放节目信息，在锁屏显示播放控制和封面等信息，他们显示的布局很合理，如果我不让系统知道当前播放信息，那么 one ui 就无法显示这些信息了。 另外有些android 第三方主题，也用到当前播放节目的信息在锁屏显示，如果获取不到就会显示空白。

**Comment by zyfzyfhaha** [comment]
好的明白了，非常感谢！
