### ISSUE TITLE
想要长按菜单里能设置已读/未读

### ISSUE THREAD

**Issue by Lynx3x** [gaodeng/Moon-FM-Support#87]
从其他播客APP兜兜转转来的，想把其他APP上的已读记录手动迁移过来，所以希望添加一个手动设置已读/未读状态的选项

**Comment by gaodeng** [comment]
不计划添加标记未听/已听 功能。
原因是标记不过来，到时候就需要一键全部标记为已听。到了这一步，就完全没有意义了，已听列表里面会充满了很多批量标记的，实际上没有听过的节目，既然这样了，为啥要标记？
