### ISSUE TITLE
关于批量加入播放列表

### ISSUE THREAD

**Issue by Adi-Sun** [gaodeng/Moon-FM-Support#88]
大佬好，很喜欢moon fm。
希望批量加入列表的时候可以避免已经从列表删除的内容，或者只添加刚刚更新的内容。（我记得原来好像是这样的，不知道哪版更新后改了）
然后能否加入一个刷新列表的时间起始点，个人有时间按顺序听的习惯，重新安装后希望能够接着之前的时间点听所有的订阅内容（听的永远赶不上更新的多T T）。谢谢～

**Comment by gaodeng** [comment]
由于绝大多数播客都是超过1个小时的，所以批量添加没有太大意义了
